name: Build Release
on: push

env:
  MIRIFLAGS: -Zmiri-disable-isolation
jobs:
  build:

    runs-on: windows-2019

    steps:
      - name: Checkout Binaries
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: miri
      - name: Install Miri
        run: cargo miri setup
      - name: Test with Miri
        run: cargo miri test