name: Build Release
on: push

jobs:
  build:

    runs-on: windows-2019

    steps:
      - name: Checkout Binaries
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
      - name: Install Miri
        run: | 
            rustup +nightly component add miri
            cargo miri setup
      - name: Test with Miri
        run: cargo miri test